In [1]:
import illustris_python as il
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
basePath ='./sims.TNG/TNG50-1/output'

In [2]:
main_subhalo_id=329508
main_halo_id=23

In [6]:
halo_fields=['Group_R_Crit200','GroupPos','GroupCM']
subhalo_fields=['SubhaloCM']

In [7]:
halosdata=il.groupcat.loadHalos(basePath, 99, fields=halo_fields)
subhalodata=il.groupcat.loadSubhalos(basePath,99, fields=subhalo_fields)

In [10]:
halosdata['GroupPos'][23]

array([  7404.5625    ,  20221.78710938,  22046.19335938], dtype=float32)

In [14]:
subhalodata[main_subhalo_id]

array([  7406.68896484,  20226.83007812,  22039.6328125 ], dtype=float32)

In [15]:
halosdata['Group_R_Crit200'][23]

316.31104

In [16]:
halosdata['GroupCM'][23]

array([  7398.60791016,  20226.94140625,  22034.50585938], dtype=float32)

In [17]:
halosdata['GroupPos'][23]

array([  7404.5625    ,  20221.78710938,  22046.19335938], dtype=float32)

In [18]:
subhalodata[main_subhalo_id]

array([  7406.68896484,  20226.83007812,  22039.6328125 ], dtype=float32)

In [19]:
halosmass=il.groupcat.loadHalos(basePath, 99, fields=['GroupMass'])

In [20]:
halosmass[23]

863.79407

In [21]:
subhalosmass=il.groupcat.loadSubhalos(basePath,99, fields=['SubhaloMass'])

In [22]:
subhalosmass[329508]

775.56519

In [3]:
r500=il.groupcat.loadHalos(basePath, 99, fields=['Group_R_Crit500'])

In [4]:
r500[23]

208.03023